# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

require "yaml"

vagrant_boxes = YAML.load_file("#{File.dirname(__FILE__)}/../../distros_supported.yml")

subnet = "10.10.13"
controller_ip = "#{subnet}.8"
debug = ENV["OS_DEBUG"] || "false"
num_compute_nodes = ENV["OS_NUM_COMPUTE_NODES"] || "2"
no_proxy = ENV["NO_PROXY"] || ENV["no_proxy"] || "127.0.0.1,localhost"
(1..254).each do |i|
  no_proxy += ",10.0.2.#{i}"
end
File.open("#{File.dirname(__FILE__)}/header.ini", "w") do |inventory_file|
  inventory_file.puts("[control]\ncontroller\n\n[network]")
  (1..num_compute_nodes.to_i).each do |i|
    inventory_file.puts("compute#{i.to_s.rjust(2, '0')}")
  end
  inventory_file.puts("\n[compute]")
  (1..num_compute_nodes.to_i).each do |i|
    inventory_file.puts("compute#{i.to_s.rjust(2, '0')}")
  end
  inventory_file.puts("\n[storage]")
  (1..num_compute_nodes.to_i).each do |i|
    inventory_file.puts("compute#{i.to_s.rjust(2, '0')}")
  end
end
hosts = "#{controller_ip}  controller\n"
(1..num_compute_nodes.to_i).each do |i|
  no_proxy += ",#{subnet}.#{i + 8}"
  hosts += "#{subnet}.#{i + 8}  compute#{i.to_s.rjust(2, '0')}\n"
end
no_proxy += ",#{controller_ip}"
socks_proxy = ENV["socks_proxy"] || ENV["SOCKS_PROXY"] || ""
local_registry_enabled = ENV["OS_ENABLE_LOCAL_REGISTRY"] || "true"
public_nic = `ip r get 1.1.1.1 | awk 'NR==1{print $5}'`.strip! || "eth0"
cloud_public_cidr = `ip r | grep "dev $(ip r get 1.1.1.1 | awk 'NR==1{print $5}') .* scope link" | awk '{print $1}'`.strip! || "192.168.0.0/24"
cloud_public_gw = `ip r | grep "^default" | awk 'NR==1{print $3}'`.strip! || "192.168.0.1"

def which(cmd)
  exts = ENV["PATHEXT"] ? ENV["PATHEXT"].split(";") : [""]
  ENV["PATH"].split(File::PATH_SEPARATOR).each do |path|
    exts.each do |ext|
      exe = File.join(path, "#{cmd}#{ext}")
      return exe if File.executable?(exe) && !File.directory?(exe)
    end
  end
  nil
end

vb_public_nic = `VBoxManage list bridgedifs | grep "^Name:.*#{public_nic}" | awk -F "Name:[ ]*" '{ print $2}'`.strip! if which "VBoxManage"
system("echo -e \"\n\n\n\" | ssh-keygen -f #{File.dirname(__FILE__)}/../../insecure_keys/key -t rsa -N ''") unless File.exist?("#{File.dirname(__FILE__)}/../../insecure_keys/key")

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt
  config.vm.provider :virtualbox

  config.vm.synced_folder "../../", "/vagrant"
  config.vm.box = vagrant_boxes["ubuntu"]["focal"]["name"]
  config.vm.box_version = vagrant_boxes["ubuntu"]["focal"]["version"]
  config.ssh.insert_key = false

  config.vm.provider :libvirt do |v, override|
    override.vm.synced_folder "../../", "/vagrant", type: "nfs"
    v.cpu_mode = "host-passthrough"
    v.random_hostname = true
    v.management_network_address = "10.0.2.0/24"
    v.management_network_name = "administration" # Administration - Provides Internet access for all nodes and is used for administration to install software packages
    v.management_network_mode = "nat" # NATed forwarding typically to reach networks outside of hypervisor
    v.cpu_mode = "host-passthrough"
    v.disk_device = "sda"
    v.disk_bus = "sata"
  end
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.customize ["modifyvm", :id, "--nictype1", "virtio", "--cableconnected1", "on"]
    # https://bugs.launchpad.net/cloud-images/+bug/1829625/comments/2
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    # Enable nested paging for memory management in hardware
    v.customize ["modifyvm", :id, "--nestedpaging", "on"]
    # Use large pages to reduce Translation Lookaside Buffers usage
    v.customize ["modifyvm", :id, "--largepages", "on"]
    # Use virtual processor identifiers  to accelerate context switching
    v.customize ["modifyvm", :id, "--vtxvpid", "on"]
  end
  config.vm.provision "shell", inline: <<~SHELL
    mkdir -p /root/.ssh
    cat /vagrant/insecure_keys/key.pub | tee /root/.ssh/authorized_keys
    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/authorized_keys
    sed -i '/^PermitRootLogin no/d' /etc/ssh/sshd_config
    # Prefer IPv4 over IPv6 in dual-stack environment
    sudo sed -i "s|^#precedence ::ffff:0:0/96  100$|precedence ::ffff:0:0/96  100|g" /etc/gai.conf
    sudo systemd-resolve --interface eth0 --set-dns 1.1.1.1 --flush-caches
    cat << EOF > /etc/hosts
    127.0.0.1   localhost
    #{hosts}
    EOF
  SHELL

  (1..num_compute_nodes.to_i).each do |i|
    config.vm.define "compute#{i.to_s.rjust(2, '0')}" do |nodeconfig|
      nodeconfig.vm.hostname = "compute#{i.to_s.rjust(2, '0')}"
      nodeconfig.vm.network :private_network, ip: "#{subnet}.#{i + 8}", type: :static, libvirt__network_name: "tunnel-net", nic_type: "virtio", virtualbox__intnet: true
      nodeconfig.vm.network :public_network, dev: public_nic, bridge: vb_public_nic, auto_config: false

      %i[virtualbox libvirt].each do |provider|
        nodeconfig.vm.provider provider do |p|
          p.memory = ENV["MEMORY"] || (4 * 1024)
        end
      end

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end
      nodeconfig.vm.disk :disk, name: "cinder", size: "50GB"

      nodeconfig.vm.provider :libvirt do |v|
        v.nested = true
        v.storage :file, bus: "sata", device: "sdb", size: 50 # Cinder volume
      end
      nodeconfig.vm.provision "shell", privileged: false do |sh|
        sh.env = {
          OPENSTACK_NODE_ROLES: "compute",
          OS_DEBUG: debug.to_s
        }
        sh.inline = <<-SHELL
          cd /vagrant
          ./node.sh -c /dev/sdb | tee ~/node_$(hostname).log
        SHELL
      end
    end
  end

  config.vm.define "controller", primary: true, autostart: false do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network :private_network, ip: controller_ip.to_s, type: :static, libvirt__network_name: "tunnel-net", nic_type: "virtio", virtualbox__intnet: true
    controller.vm.network :public_network, dev: public_nic, bridge: vb_public_nic, auto_config: false
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
      cd /vagrant
      sudo mkdir -p /root/.ssh/
      sudo cp insecure_keys/key /root/.ssh/id_rsa
      cp insecure_keys/key ~/.ssh/id_rsa
      cp insecure_keys/key.pub ~/.ssh/id_rsa.pub
      sudo chmod 400 /root/.ssh/id_rsa
      chown "$USER" ~/.ssh/id_rsa
      chmod 400 ~/.ssh/id_rsa

      source /etc/os-release || source /usr/lib/os-release
      case ${ID,,} in
          ubuntu|debian)
              sudo apt-get update ||:
              sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --reinstall --no-install-recommends ca-certificates
              sudo update-ca-certificates

              if ! command -v curl; then
                  sudo apt-get update
                  sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl
              fi
          ;;
      esac
    SHELL
    controller.vm.provision "shell", privileged: false do |sh|
      sh.env = {
        SOCKS_PROXY: socks_proxy.to_s,
        OS_FOLDER: "/vagrant/",
        OS_DEBUG: debug.to_s,
        OS_ENABLE_LOCAL_REGISTRY: local_registry_enabled.to_s,
        OS_INVENTORY_FILE: "./samples/noha/hosts.ini",
        OS_KOLLA_API_INTERFACE: "eth1",
        OS_KOLLA_NEUTRON_EXTERNAL_INTERFACE: "eth2",
        OS_KOLLA_KOLLA_INTERNAL_VIP_ADDRESS: controller_ip.to_s,
        EXT_NET_RANGE: "start=#{cloud_public_cidr.sub('0/24', '50')},end=#{cloud_public_cidr.sub('0/24', '100')}",
        EXT_NET_CIDR: cloud_public_cidr.to_s,
        EXT_NET_GATEWAY: cloud_public_gw.to_s
      }
      sh.inline = <<-SHELL
        set -o errexit

        for krd_var in $(printenv | grep "OS_\|EXT_NET_" ); do echo "export $env_var" | sudo tee --append /etc/environment ; done

        cd /vagrant

        # Create ansible inventory file
        pushd samples/noha/
        rm -f $(basename $OS_INVENTORY_FILE)
        cat header.ini | tee --append $(basename $OS_INVENTORY_FILE)
        cat tail.ini | tee --append  $(basename $OS_INVENTORY_FILE)
        popd

        ./node.sh -v sdb=/var/lib/docker/ | tee ~/node_controller.log
        ./install.sh | tee ~/install_controller.log
      SHELL
    end
    %i[virtualbox libvirt].each do |provider|
      config.vm.provider provider do |p|
        p.cpus = ENV["CPUS"] || 4
        p.memory = ENV["MEMORY"] || (8 * 1024)
      end
    end

    # Volumes
    controller.vm.disk :disk, name: "docker", size: "50GB"
    controller.vm.provider :libvirt do |v|
      v.storage :file, bus: "sata", device: "sdb", size: 50
    end
  end

  if !ENV["http_proxy"].nil? && !ENV["https_proxy"].nil? && Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = ENV["http_proxy"] || ENV["HTTP_PROXY"] || ""
    config.proxy.https    = ENV["https_proxy"] || ENV["HTTPS_PROXY"] || ""
    config.proxy.no_proxy = no_proxy
    config.proxy.enabled = { docker: false }
  end
end
