---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
jobs:
  include:
    - name: Lint validation
      language: python
      install:
        - pip install tox
      script:
        - tox -e bashate
        - bash -c 'shopt -s globstar; shellcheck -x **/*.sh'
    - name: All-in-One Ubuntu 18.04 LTS Bare Metal validation
      install:
        - sudo apt-get update
        - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 bridge-utils
      before_script:
        - sudo ip link add veth0 type veth peer name veth1
        - sudo ip addr add 10.10.13.7/24 dev veth0
        - sudo ip link set veth0 up
        - sudo brctl addbr uplinkbridge
        - sudo brctl addif uplinkbridge veth0
        - sudo ip link set dev uplinkbridge up
        - echo "127.0.0.1 localhost" | sudo tee /etc/hosts
      script:
        - ./node.sh
        - sed -i "s|localhost|$(hostname)|g" samples/aio/hosts.ini
        - OS_FOLDER=$(git rev-parse --show-toplevel) ./install.sh
      after_success:
        - openstack hypervisor list
      env:
        - OS_KOLLA_ENABLE_CINDER=no
    - name: All-in-One CentOS 8 Vagrant validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
      script:
        - cd samples/aio/; sudo -E vagrant up
      env:
        - MEMORY=7168
        - CPUS=2
        - CORES=2
        - THREADS=1
        - OS_KOLLA_RUN_INIT=false
    - name: OpenStack Kolla images validation
      script:
        - ./registry.sh
      after_success:
        - sudo docker images
        - curl -s -X GET http://localhost:5000/v2/_catalog | jq -r '.repositories'
      env:
        - OS_KOLLA_BUILD_ARGS='keystone --registry 127.0.0.1:5000 --push --threads 4 --quiet --retries 5 --cache --push-threads 2 --squash'
