---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
install:
  - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
  - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
script:
  - cd samples/aio/; sudo -E vagrant up
env:
  - MEMORY=7168 CPUS=2 CORES=2 THREADS=1 OS_KOLLA_RUN_INIT=false
