---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Docker image
description: Analyzes security vulnerabilities and size of a given docker image
inputs:
  image:
    description: Docker image name
runs:
  using: "composite"
  steps:
    - name: Get Docker Image layer contents
      uses: MaxymVlasov/dive-action@9bfaea6c0b1e49111459b2cb3f9275fa4094a63e # v2.0.1
      with:
        image: ${{ inputs.image }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        image-ref: "${{ inputs.image }}"
        format: sarif
        output: results.sarif
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
      with:
        sarif_file: results.sarif
        category: "${{ inputs.image }}"
