---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Docker image
description: Analyzes security vulnerabilities and size of a given docker image
inputs:
  image:
    description: Docker image name
runs:
  using: "composite"
  steps:
    - name: Get Docker Image layer contents
      uses: MaxymVlasov/dive-action@b08c8287e603d028c986d7044e83fa76bcca6a65 # 1.5.0
      with:
        image: ${{ inputs.image }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0
      with:
        image-ref: "${{ inputs.image }}"
        format: sarif
        output: results.sarif
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@86b04fb0e47484f7282357688f21d5d0e32175fe # 3.26.9
      with:
        sarif_file: results.sarif
        category: "${{ inputs.image }}"
