---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Docker image
description: Analyzes security vulnerabilities and size of a given docker image
inputs:
  image:
    description: Docker image name
runs:
  using: "composite"
  steps:
    - name: Get Docker Image layer contents
      uses: MaxymVlasov/dive-action@fafb796951b322cc4926b8a5eafda89ab9de8edf # 1.5.1
      with:
        image: ${{ inputs.image }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        image-ref: "${{ inputs.image }}"
        format: sarif
        output: results.sarif
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@86b04fb0e47484f7282357688f21d5d0e32175fe # 3.26.9
      with:
        sarif_file: results.sarif
        category: "${{ inputs.image }}"
