---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Scheduled Kolla Images Build verification
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - registry.sh
      - etc/kolla/kolla-build.ini
  pull_request_review:
    types:
      - submitted
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  build-baremetal:
    name: Check building and publishing Kolla Docker images in a local Docker registry on an Ubuntu Jammy Virtual Environment
    runs-on: ubuntu-22.04
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Install requirements
        env:
          OS_KOLLA_BUILD_ARGS: 'keystone --registry 127.0.0.1:5000 --push --threads 4 --quiet --retries 5 --cache --push-threads 2 --squash --base ubuntu'
        run: ./registry.sh
      - name: Validate images
        run: |
          sudo docker images
          curl -s -X GET http://localhost:5000/v2/_catalog | jq -r '.repositories'
  build-virtual_machines:
    name: Check building and publishing Kolla Docker images in a local Docker registry Virtual Machines
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu_22
            image: nova
          - distro: rocky_9
            image: glance
          - distro: debian_11
            image: neutron
    runs-on: macos-12
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/vagrant-setup
        with:
          distro: ${{ matrix.distro }}
      - name: Deploy All-in-One instance
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          OS_DISTRO: ${{ matrix.distro }}
          OS_KOLLA_BUILD_ARGS: ${{ matrix.image }} --registry 127.0.0.1:5000 --push --threads 2 --quiet --retries 5 --cache --push-threads 2 --base ${{ matrix.distro }}
        working-directory: ./samples/distributed
        run: vagrant up registry
