---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Build Kolla Images
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - registry.sh
      - etc/kolla/kolla-build.ini
  pull_request_review:
    types:
      - submitted
    paths:
      - registry.sh
      - etc/kolla/kolla-build.ini
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-keystone-ubuntu-images:
    name: Check building and publishing Kolla Docker images in a local Docker registry on an Ubuntu Focal Virtual Environment
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        env:
          OS_KOLLA_BUILD_ARGS: 'keystone --registry 127.0.0.1:5000 --push --threads 4 --quiet --retries 5 --cache --push-threads 2 --squash --base ubuntu'
        run: ./registry.sh
      - name: Validate images
        run: |
          sudo docker images
          curl -s -X GET http://localhost:5000/v2/_catalog | jq -r '.repositories'
  build-keystone-centos-images:
    name: Check building and publishing Kolla Docker images in a local Docker registry on an CentOS 8 Virtual Machine
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('distros_supported.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
          find . -type f -name "*.bak" -delete
      - name: Deploy All-in-One instance
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          OS_DISTRO: centos
          OS_KOLLA_BUILD_ARGS: 'glance --registry 127.0.0.1:5000 --push --threads 2 --quiet --retries 5 --cache --push-threads 2 --base centos'
        run: cd samples/distributed/; vagrant up registry
