---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Build Kolla Images
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - registry.sh
      - etc/kolla/kolla-build.ini
  pull_request_review:
    types:
      - submitted
    paths:
      - registry.sh
      - etc/kolla/kolla-build.ini
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-images:
    name: Check building and publishing Kolla Docker images in a local Docker registry
    runs-on: ubuntu-18.04
    env:
      OS_KOLLA_BUILD_ARGS: 'keystone --registry 127.0.0.1:5000 --push --threads 4 --quiet --retries 5 --cache --push-threads 2 --squash'
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: ./registry.sh
      - name: Validate images
        run: |
          sudo docker images
          curl -s -X GET http://localhost:5000/v2/_catalog | jq -r '.repositories'
