---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Bare-Metal installations
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check-ubuntu-bionic:
    runs-on: ubuntu-18.04
    env:
      OS_KOLLA_ENABLE_CINDER: no
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 bridge-utils
      - name: Setup network external interface
        run: |
          sudo ip link add veth0 type veth peer name veth1
          sudo ip addr add 10.10.13.7/24 dev veth0
          sudo ip link set veth0 up
          sudo brctl addbr uplinkbridge
          sudo brctl addif uplinkbridge veth0
          sudo ip link set dev uplinkbridge up
          echo "127.0.0.1 localhost" | sudo tee /etc/hosts
      - name: Deploy services
        run: |
          ./node.sh
          sed -i "s|localhost|$(hostname)|g" samples/aio/hosts.ini
          OS_FOLDER=$(git rev-parse --show-toplevel) ./install.sh
      - name: Deploy services
        run: openstack hypervisor list
  build-images:
    runs-on: ubuntu-18.04
    env:
      OS_KOLLA_BUILD_ARGS: 'keystone --registry 127.0.0.1:5000 --push --threads 4 --quiet --retries 5 --cache --push-threads 2 --squash'
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: ./registry.sh
      - name: Validate images
        run: |
          sudo docker images
          curl -s -X GET http://localhost:5000/v2/_catalog | jq -r '.repositories'
