---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Lint Code Base
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
permissions: read-all
jobs:
  get-sloc:
    name: Count Lines of Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # 6.0.0
        with:
          go-version: ">=1.20.0"
      - name: Install dependencies
        run: go install github.com/boyter/scc/v3@latest
      - name: Run scc tool
        run: scc --format wide
  check-broken-links:
    name: Check documentation external links
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Check broken links
        uses: tcort/github-action-markdown-link-check@f3d33029dca1c4a24b87e2df648f9f4604ef6533 # 1.1.1
  check-super-linter:
    name: Check syntax (super-linter)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - uses: super-linter/super-linter@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # 8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          EDITORCONFIG_FILE_NAME: .editorconfig-checker.json
          FILTER_REGEX_EXCLUDE: "requirements/.*"
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_BIOME_FORMAT: false
          DEFAULT_BRANCH: ${{ github.head_ref || github.ref_name }}
  check-tox:
    name: Check syntax (tox)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          persist-credentials: false
      - name: Install tox
        run: python -m pip install tox --break-system-packages
      - name: Run tox lint validation
        run: tox -e lint
