---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All - All-in-One setup
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-centos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
      - name: Deploy All-in-One instance
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          CPUS: 2
          CORES: 2
          THREADS: 1
          MEMORY: 12288
          OS_KOLLA_RUN_INIT: false
        run: cd samples/aio/; vagrant up
  check-ubuntu:
    runs-on: ubuntu-20.04
    env:
      OS_KOLLA_ENABLE_CINDER: no
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 bridge-utils
      - name: Setup network external interface
        run: |
          sudo ip link add veth0 type veth peer name veth1
          sudo ip addr add 10.10.13.7/24 dev veth0
          sudo ip link set veth0 up
          sudo brctl addbr uplinkbridge
          sudo brctl addif uplinkbridge veth0
          sudo ip link set dev uplinkbridge up
          echo "127.0.0.1 localhost" | sudo tee /etc/hosts
      - name: Deploy services
        run: |
          ./node.sh
          sed -i "s|localhost|$(hostname)|g" samples/aio/hosts.ini
          OS_FOLDER=$(git rev-parse --show-toplevel) ./install.sh
