---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All-in-One setup
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '*.sh'
      - '*.yml'
      - 'samples/aio/*'
      - 'etc/**'
      - '!.github/**'
  pull_request_review:
    types:
      - submitted
    paths:
      - '*.sh'
      - '*.yml'
      - 'samples/aio/*'
      - 'etc/**'
      - '!.github/**'

jobs:
  check-aio-vms:
    name: Check All-in-One deployment on Virtual Machines
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu, centos, debian]
    runs-on: macos-10.15
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('distros_supported.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      # TODO: Remove this once https://www.virtualbox.org/ticket/20636 is released
      - name: Apply workaround for VBoxHeadless in macOS
        run: |
          find . -type f -iname "Vagrantfile" -exec sed -i '.bak' 's|v.gui = .*|v.gui = true|g' {} \;
          find . -type f -name "*.bak" -delete
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
          find . -type f -name "*.bak" -delete
      - name: Deploy All-in-One instance
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          VAGRANT_EXPERIMENTAL: disks
          CPUS: 2
          MEMORY: 12288
          OS_KOLLA_RUN_INIT: false
          OS_DISTRO: ${{ matrix.distro }}
        run: cd samples/aio/; vagrant up
  check-aio-baremetal:
    runs-on: ubuntu-20.04
    name: Check All-in-One deployment on Ubuntu Focal Virtual Environment
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    env:
      OS_KOLLA_ENABLE_CINDER: no
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends bridge-utils python3-testresources
      - name: Setup network external interface
        run: |
          sudo ip link add veth0 type veth peer name veth1
          sudo ip link set veth0 up
          sudo brctl addbr uplinkbridge
          sudo brctl addif uplinkbridge veth0
          sudo ip link set dev uplinkbridge up
          sudo ip addr add 10.10.13.7/24 dev veth0
          sudo ip route show

          echo "127.0.0.1 localhost" | sudo tee /etc/hosts
      - name: Deploy services
        env:
          OS_DEBUG: true
        run: |
          ./node.sh
          sed -i "s|localhost|$(hostname)|g" samples/aio/hosts.ini
          OS_FOLDER=$(git rev-parse --show-toplevel) ./install.sh
