---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check No High Availability setup
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '*.sh'
      - '*.yml'
      - 'samples/noha/*'
      - 'etc/**'
      - '!.github/**'
  pull_request_review:
    types:
      - submitted
    paths:
      - '*.sh'
      - '*.yml'
      - 'samples/noha/*'
      - 'etc/**'
      - '!.github/**'

jobs:
  check-noha-ubuntu:
    name: Check No High Availability deployment on Ubuntu Focal Virtual Machines
    runs-on: macos-10.15
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) ||
      github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('distros_supported.yml') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
          find . -type f -name "*.bak" -delete
      - name: Install GNU tools
        run: brew install iproute2mac
      - name: Deploy OpenStack nodes
        env:
          VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
          VAGRANT_EXPERIMENTAL: disks
          OS_NUM_COMPUTE_NODES: 1
        run: |
          cd samples/noha/
          MEMORY=4096 CPUS=1 vagrant up
          MEMORY=8192 CPUS=2 vagrant up controller
