---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Check No High Availability setup
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - "*.sh"
      - "*.yml"
      - "samples/noha/*"
      - "etc/**"
      - "!.github/**"
  pull_request_review:
    types:
      - submitted
permissions: read-all
jobs:
  check-noha-ubuntu:
    name: Check No High Availability deployment on Ubuntu Focal Virtual Machines
    runs-on: vm-self-hosted
    if: >-
      ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) || github.event_name != 'pull_request_review'
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
      VAGRANT_EXPERIMENTAL: disks
      OS_NUM_COMPUTE_NODES: 1
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
      - uses: ./.github/actions/vagrant-setup
      - name: Install Vagrant Reload plugin
        run: vagrant plugin install vagrant-reload
      - name: Deploy OpenStack Compute nodes
        env:
          MEMORY: 12288
          CPU: 3
        working-directory: ./samples/noha
        run: vagrant up compute01
      - name: Reload OpenStack Compute nodes
        env:
          MEMORY: 4096
          CPU: 1
        working-directory: ./samples/noha
        run: vagrant reload compute01
        # NOTE: macOS provides 3 vCPUS and 14 GB of RAM (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
      - name: Deploy OpenStack Control nodes
        env:
          OS_DEBUG: true
          OS_ENABLE_LOCAL_REGISTRY: false
          MEMORY: 8192
          CPU: 2
        working-directory: ./samples/noha
        run: vagrant up controller
      - name: Check HW resources
        if: failure()
        run: |
          VBoxManage list runningvms --long
          cat ~/VirtualBox\ VMs/*/Logs/*.log
