---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Check All-in-One setup
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '*.sh'
      - '*.yml'
      - 'samples/aio/*'
      - 'etc/**'
      - '!.github/**'
  pull_request_review:
    types:
      - submitted
jobs:
  generate-json-matrix:
    runs-on: ubuntu-latest
    if: >-
      (

        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) || github.event_name != 'pull_request_review'
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Get matrix values
        id: set-matrix
        run: |
          if ! command -v shyaml; then
              if ! command -v pip; then
                  apt-get update
                  apt-get install -y --no-install-recommends python3-pip
              fi
              pip install shyaml
          fi
          if ! command -v jq; then
              apt-get update
              apt-get install -y --no-install-recommends jq
          fi
          echo "matrix=$(shyaml keys < distros_supported.yml|jq -cnR '[inputs | select(length>0)]')" >>"$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  check-aio-vms:
    name: Check All-in-One deployment on Virtual Machines
    needs: generate-json-matrix
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJson(needs.generate-json-matrix.outputs.matrix) }}
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: ./.github/actions/vagrant-setup
        with:
          distro: ${{ matrix.distro }}
      - name: Deploy previous release in All-in-One instance
        env:
          CPUS: 2
          MEMORY: 12288
          OS_DISTRO: ${{ matrix.distro }}
        run: ./ci/check_aio.sh
  check-aio-baremetal:
    runs-on: ubuntu-22.04
    name: Check All-in-One deployment on Ubuntu Jammy Virtual Environment
    if: >-
      (

        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) || github.event_name != 'pull_request_review'
    env:
      OS_KOLLA_ENABLE_CINDER: "no"
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends bridge-utils python3-testresources
      - name: Setup network external interface
        run: |
          sudo ip link add veth0 type veth peer name veth1
          sudo ip link set veth0 up
          sudo brctl addbr uplinkbridge
          sudo brctl addif uplinkbridge veth0
          sudo ip link set dev uplinkbridge up
          sudo ip addr add 10.10.13.7/24 dev veth0
          sudo ip route show

          echo "127.0.0.1 localhost" | sudo tee /etc/hosts
      - name: Deploy services
        env:
          OS_DEBUG: true
        run: |
          ./node.sh
          sed -i "s|localhost|$(hostname)|g" samples/aio/hosts.ini
          OS_FOLDER=$(git rev-parse --show-toplevel) ./install.sh
