---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check All - No High Availability setup
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-ubuntu:
    runs-on: macos-10.15
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
      OS_NUM_COMPUTE_NODES: 1
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Replace shorten links
        run: |
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_pkg|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh|g' {} \;
          find . -type f -iname "*sh" -exec sed -i '.bak' 's|http://bit.ly/install_bin|https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh|g' {} \;
      - name: Install GNU tools
        run: brew install iproute2mac
      - name: Deploy Compute nodes
        env:
          MEMORY: 4096
          CPUS: 1
          VAGRANT_EXPERIMENTAL: disks
        run: cd samples/noha/; vagrant up
      - name: Deploy Controller node
        env:
          OS_ENABLE_LOCAL_REGISTRY: false
          MEMORY: 8192
          CPUS: 2
        run: cd samples/noha/; vagrant up controller
