---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Scheduled Versions and Dictionary verification
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install dependencies
        run: pip install tox
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            tox -e update
          COMMIT_MESSAGE: 'Upgrade OpenStack Kolla dependencies'
          COMMIT_NAME: 'electrocucaracha bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update versions'
  check-dictionary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            sudo apt-get update
            sudo apt-get -y --no-install-recommends install aspell aspell-en
            pip install pyspelling

            sort --ignore-case --output=original.dic .github/.wordlist.txt
            echo "" > .github/.wordlist.txt
            # Remove leftovers
            pyspelling -c .spellcheck.yml | sed '/^<.*>/d;/^!!!/d;/^--/d;/^Misspelled words:/d;/^$/d;/^Spelling check passed :)$/d' | sort --ignore-case | uniq --ignore-case | tee draft.dic
            comm -12 --nocheck-order draft.dic original.dic > .github/.wordlist.txt
            sort --ignore-case --output=.github/.wordlist.txt .github/.wordlist.txt

            # Add missing words
            pyspelling -c .spellcheck.yml | sed '/^<.*>/d;/^!!!/d;/^--/d;/^Misspelled words:/d;/^$/d;/^Spelling check passed :)$/d' | sort --ignore-case | uniq --ignore-case | tee --append .github/.wordlist.txt
            sort --ignore-case --output=.github/.wordlist.txt .github/.wordlist.txt
          COMMIT_MESSAGE: 'Update dictionary definitions'
          COMMIT_NAME: 'spellchecker bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update dictionary'
